steps:
  - name: 'node:22-alpine'
    args:
      - 'sh'
      - '-c'
      - 'yarn install'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hexagun-mx/portfolio', '.']
options:
  logging: CLOUD_LOGGING_ONLY